//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/Init")]
        void Init(string keyPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/Init")]
        System.Threading.Tasks.Task InitAsync(string keyPath);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/Write")]
        void Write(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnitService/Write")]
        System.Threading.Tasks.Task WriteAsync(string message, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference1.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference1.IRealTimeUnitService>, RealTimeUnit.ServiceReference1.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init(string keyPath) {
            base.Channel.Init(keyPath);
        }
        
        public System.Threading.Tasks.Task InitAsync(string keyPath) {
            return base.Channel.InitAsync(keyPath);
        }
        
        public void Write(string message, byte[] signature) {
            base.Channel.Write(message, signature);
        }
        
        public System.Threading.Tasks.Task WriteAsync(string message, byte[] signature) {
            return base.Channel.WriteAsync(message, signature);
        }
    }
}
